In [1]:
import sys
sys.path.append('..')
import numpy as np

import networks

Couldn't import dot_parser, loading of dot files will not be possible.


Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled)


In [2]:
network = networks.stn()

In [15]:
test_ref = np.random.randn(32, 512, 512).astype('float32')
test_input = np.random.randn(32, 2,  512, 512).astype('float32')

In [4]:
network.get_shape_1(test_ref)

array([    32, 262144])

In [5]:
network.get_shape_2(test_ref)

array([    32, 262144])

In [6]:
max_shape, min_shape = network.get_max_min_shape(test_ref)
print max_shape
print min_shape

[32  1]
[32  1]


In [7]:
network.get_norm_shape(test_ref)

array([    32, 262144])

In [12]:
ref_norm = network.get_ref_norm(test_ref)
print ref_norm

[[ 0.47155672  0.46467742  0.53074825 ...,  0.52420372  0.57487464
   0.21859114]
 [ 0.53151751  0.58280981  0.67636657 ...,  0.61685473  0.69094819
   0.28599432]
 [ 0.47452766  0.55346107  0.33348051 ...,  0.36708179  0.4290038
   0.33820334]
 ..., 
 [ 0.50877917  0.38340306  0.43615687 ...,  0.47129363  0.57775712
   0.30611476]
 [ 0.622118    0.56285453  0.60737514 ...,  0.67576396  0.54789644
   0.3101992 ]
 [ 0.56089497  0.53816503  0.53001302 ...,  0.75910008  0.7358377
   0.62872815]]


In [14]:
np.allclose(ref_norm.sum(axis=1), norm_sum)

True

In [9]:
norm_max, norm_min = network.get_norm_max_min(test_ref)
print np.unique(norm_max)
print np.unique(norm_min)

[ 1.]
[ 0.]


In [11]:
norm_sum, part_sum = network.new_sum(test_ref)
print norm_sum
print part_sum

[ 127905.484375   128338.         132405.15625    132753.34375
  124923.4609375  130575.         133343.765625   127737.9453125
  129573.03125    128182.453125   133820.171875   130224.2109375
  140263.125      127612.1875     143731.515625   131173.34375
  125458.109375   133360.625      126501.7421875  126860.171875
  135228.21875    136670.984375   134460.71875    133298.421875   131939.375
  131985.4375     139778.8125     127963.359375   128479.0234375
  127711.84375    126745.8125     133771.625    ]
[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.
  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [ ]:
test_ref_reshape = np.reshape(test_ref, (32, -1))
test_ref_reshape.shape

In [ ]:
test_ref_reshape.max(axis=1).shape

In [16]:
network.get_cost(test_input, test_ref)

array(7.633152563357726e-06, dtype=float32)